In [102]:
import pandas as pd
import csv
path_list=[3,4,5]
tt=pd.DataFrame()
for n in path_list:
    f = open('亚马逊%d月.csv'%n,'r',encoding='utf-8')
    reader = csv.reader(f)
    t1 = pd.DataFrame(reader,dtype=str)
    t1=t1.iloc[7:]
    t1.columns=t1.iloc[0]
    t1=t1.reset_index(drop=True)
    tt=pd.concat([t1,tt])
    
tt=tt.drop(tt[tt['date/time']=='date/time'].index)
tt

7,date/time,settlement id,type,order id,sku,description,quantity,marketplace,account type,fulfillment,...,Regulatory Fee,Tax On Regulatory Fee,promotional rebates,promotional rebates tax,marketplace withheld tax,selling fees,fba fees,other transaction fees,other,total
1,"May 1, 2022 12:55:54 AM PDT",15838702931,Order,111-1394300-5467431,80cm31.5inchFWX,360 Photo Booth Machine for Parties with Free ...,1,amazon.com,Standard Orders,Amazon,...,0,0,0,0,-206.31,-198.92,-53.68,0,0,"2,146.40"
2,"May 1, 2022 4:29:47 AM PDT",15838702931,Service Fee,,,Cost of Advertising,,,Standard Orders,,...,0,0,0,0,0,0,0,-501.93,0,-501.93
3,"May 2, 2022 3:00:24 AM PDT",15870045011,Service Fee,,,Cost of Advertising,,,Standard Orders,,...,0,0,0,0,0,0,0,-372.93,0,-372.93
4,"May 2, 2022 5:26:55 AM PDT",15870045011,Transfer,,,"To your account ending in: 121, Bank Transfer ...",,,Standard Orders,,...,0,0,0,0,0,0,0,0,"-8,258.04","-8,258.04"
5,"May 2, 2022 11:11:29 AM PDT",15870045011,Order,111-2684115-3325850,80cm31.5inchFWX,360 Photo Booth Machine for Parties with Free ...,1,amazon.com,Standard Orders,Amazon,...,0,0,0,0,-194.92,0,-53.68,0,0,"2,345.32"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32,"Mar 27, 2022 8:38:25 AM PDT",15560763051,Fee Adjustment,111-1732688-6669868,,Fee Adjustment - Weight and Dimension Change,,Amazon.com,Standard Orders,,...,0,0,0,0,0,0,61.25,0,0,61.25
33,"Mar 27, 2022 12:11:12 PM PDT",15560763051,Service Fee,,,Cost of Advertising,,,Standard Orders,,...,0,0,0,0,0,0,0,-511.71,0,-511.71
34,"Mar 29, 2022 1:47:50 AM PDT",15695148511,Transfer,,,"To your account ending in: 121, Bank Transfer ...",,,Standard Orders,,...,0,0,0,0,0,0,0,0,"-6,583.33","-6,583.33"
35,"Mar 29, 2022 5:48:32 PM PDT",15695148511,Service Fee,,,Cost of Advertising,,,Standard Orders,,...,0,0,0,0,0,0,0,-505.07,0,-505.07
36,"Mar 31, 2022 5:14:15 PM PDT",15695148511,Order,113-6128815-5910621,00-V0PZ-WG22,olylo 360 Photo Booth Machine for Parties Peop...,1,amazon.com,Standard Orders,Amazon,...,0,0,0,0,0,0,0,0,0,0

In [103]:
tt.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 252 entries, 1 to 36
Data columns (total 30 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   date/time                 252 non-null    object
 1   settlement id             252 non-null    object
 2   type                      252 non-null    object
 3   order id                  252 non-null    object
 4   sku                       252 non-null    object
 5   description               252 non-null    object
 6   quantity                  252 non-null    object
 7   marketplace               252 non-null    object
 8   account type              252 non-null    object
 9   fulfillment               252 non-null    object
 10  order city                252 non-null    object
 11  order state               252 non-null    object
 12  order postal              252 non-null    object
 13  tax collection model      252 non-null    object
 14  product sales             252 non-null    object
 15  product sales tax         252 non-null    object
 16  shipping credits          252 non-null    object
 17  shipping credits tax      252 non-null    object
 18  gift wrap credits         252 non-null    object
 19  giftwrap credits tax      252 non-null    object
 20  Regulatory Fee            252 non-null    object
 21  Tax On Regulatory Fee     252 non-null    object
 22  promotional rebates       252 non-null    object
 23  promotional rebates tax   252 non-null    object
 24  marketplace withheld tax  252 non-null    object
 25  selling fees              252 non-null    object
 26  fba fees                  252 non-null    object
 27  other transaction fees    252 non-null    object
 28  other                     252 non-null    object
 29  total                     252 non-null    object
dtypes: object(30)
memory usage: 61.0+ KB

In [112]:
tt_order_info=tt[tt['type']=='Order']
tt_order_info=tt_order_info[['date/time', 'order id','sku','quantity','fulfillment','order city','order state','order postal','product sales','product sales tax','shipping credits','shipping credits tax','gift wrap credits','giftwrap credits tax','Regulatory Fee','Tax On Regulatory Fee','promotional rebates','promotional rebates tax','marketplace withheld tax','selling fees','fba fees','other transaction fees','other','total']]
ss=tt_order_info['date/time'].str.split(' ', expand=True)
tt_order_info.drop('date/time',axis=1,inplace=True)
tt_order_info.insert(0,'日期',ss[2].str.cat([ss[0],ss[1].str[:-1]],sep='-',na_rep='?'))
tt_order_info.insert(1,'时间',ss[3])
tt_order_info

7,日期,时间,order id,sku,quantity,fulfillment,order city,order state,order postal,product sales,...,Regulatory Fee,Tax On Regulatory Fee,promotional rebates,promotional rebates tax,marketplace withheld tax,selling fees,fba fees,other transaction fees,other,total
1,2022-May-1,12:55:54,111-1394300-5467431,80cm31.5inchFWX,1,Amazon,PHOENIX,AZ,85035-2085,"2,399.00",...,0,0,0,0,-206.31,-198.92,-53.68,0,0,"2,146.40"
5,2022-May-2,11:11:29,111-2684115-3325850,80cm31.5inchFWX,1,Amazon,MONROE,NY,10950-2519,"2,399.00",...,0,0,0,0,-194.92,0,-53.68,0,0,"2,345.32"
7,2022-May-3,12:23:50,113-6312516-3045007,PB-Logo,1,Seller,LOWELL,MI,49331-8893,80.00,...,0,0,-2.49,0,-4.65,-11.63,0,0,0,65.88
8,2022-May-3,12:24:07,114-2439099-8582602,115F-FBM,1,Seller,FORNEY,TX,75126-3858,"3,299.00",...,0,0,0,0,-206.19,0,0,0,0,"3,299.00"
9,2022-May-3,12:24:21,112-2309071-5573023,115F-FBM,1,Seller,PIEDMONT,SC,29673-9691,"3,299.00",...,0,0,0,0,-197.94,-270.92,0,0,0,"3,028.08"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24,2022-Mar-24,1:03:50,112-1811603-2712259,00-V0PZ-WG22,1,Amazon,NEW YORK,NY,10029-3683,"2,699.00",...,0,0,-62.89,0,-239.54,-222.92,-120.61,0,0,"2,355.47"
25,2022-Mar-24,4:29:39,112-9625276-7789039,E5-VSV4-XXLM,1,Amazon,BALTIMORE,MD,21213-1830,"2,699.00",...,0,0,0,0,-161.94,-222.92,-73.12,0,0,"2,402.96"
26,2022-Mar-24,4:57:31,111-2483470-4428244,CD-4SH3-C0UB,1,Amazon,SPRINGFIELD,MA,01109-3001,"3,199.00",...,0,0,0,0,-199.94,-262.92,-188.18,0,0,"2,747.90"
27,2022-Mar-24,5:18:53,111-1985416-9297854,Bark Collar for B800,1,Amazon,Surprise,AZ,85379,40.99,...,0,0,0,0,-3.48,-6.15,-3.88,0,0,30.96
36,2022-Mar-31,5:14:15,113-6128815-5910621,00-V0PZ-WG22,1,Amazon,HAMPTON,GA,30228-2195,0,...,0,0,0,0,0,0,0,0,0,0

In [113]:
import mysql
from mysql import connector

mydb = mysql.connector.connect(
  host="localhost",  # 默认用主机名
    user="root",  # 默认用户名
    password="87885471", # mysql密码
    charset='utf8'  # 编码方式
)

mycursor = mydb.cursor()

mycursor.execute("SHOW DATABASES")

for x in mycursor:
  print(x)

NameError: name 'mysql' is not defined